<Project Sdk="Tomat.Terraria.ModLoader.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

        <TmlBuildUseDefaultModImpl>true</TmlBuildUseDefaultModImpl>
    </PropertyGroup>
    
    <PropertyGroup>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    </PropertyGroup>

    <ItemGroup>
        <Publicize Include="FNA;ReLogic;Terraria" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
    </ItemGroup>
    
    <ItemGroup>
        <AdditionalFiles Remove="Assets\Effects\.compile\**" />
        <Compile Remove="Assets\Effects\.compile\**" />
        <EmbeddedResource Remove="Assets\Effects\.compile\**" />
        <None Remove="Assets\Effects\.compile\**" />
    </ItemGroup>

<!--    <ItemGroup>-->
<!--      <ProjectReference Include="..\EvilExpansionMod.Generation\EvilExpansionMod.Generation.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />-->
<!--    </ItemGroup>-->

    <ItemGroup>
        <AdditionalFiles Include="Assets/**/*.png" />
        <AdditionalFiles Include="Assets/**/*.fxc" />
        <AdditionalFiles Include="Assets/**/*.wav" />
        <AdditionalFiles Include="Assets/**/*.ogg" />
        <AdditionalFiles Include="Assets/**/*.mp3" />
    </ItemGroup>
</Project>