<Project Sdk="Tomat.Terraria.ModLoader.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

        <TmlBuildUseDefaultModImpl>true</TmlBuildUseDefaultModImpl>

        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
    </PropertyGroup>
    
    <PropertyGroup>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    </PropertyGroup>

    <ItemGroup>
        <Publicize Include="FNA;ReLogic;Terraria" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Daybreak">
            <HintPath>lib\Daybreak.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>