using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace EvilExpansionMod.Generation;

[Generator(LanguageNames.CSharp)]
public class AssetsGenerator : IIncrementalGenerator {
    static readonly string[] TextureExtensions = [".png"];
    static readonly string[] EffectExtensions = [".fxc"];
    static readonly string[] AudioExtensions = [".ogg"];

    // NOTE: Most likely faster than a hashset if there is so few extensions.
    static readonly string[] AllExtensions = TextureExtensions
        .Concat(EffectExtensions)
        .Concat(AudioExtensions)
        .ToArray();

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context) {
        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
                options.GlobalOptions.TryGetValue("build_property.rootnamespace", out var ns) && !string.IsNullOrWhiteSpace(ns)
                    ? ns
                    : "Assets");

        var projectDir = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
                options.GlobalOptions.TryGetValue("build_property.ProjectDir", out var ns) && !string.IsNullOrWhiteSpace(ns)
                    ? ns
                    : throw new InvalidOperationException("no project directory"));

        var contents = context.AdditionalTextsProvider
            .Where(static file => AllExtensions.Contains(Path.GetExtension(file.Path)))
            .Combine(projectDir)
            .Select(static (t, _) =>
            {
                string path = t.Left.Path[t.Right.Length..].Replace('\\', '/');
                string directory = Path.GetDirectoryName(path)!.Replace('\\', '/');

                return (Directory: directory, Path: path);
            })
            .Where(static t => t.Path.StartsWith("Assets/"))
            .Collect()
            .SelectMany((files, _) =>
                files
                    .GroupBy(
                        f => f.Directory,
                        f => f.Path,
                        (directory, paths) => (directory, paths.ToImmutableArray()))
                    .ToImmutableArray()
            )
            .Combine(rootNamespace);

        var builder = new StringBuilder(2048);
        context.RegisterSourceOutput(
            contents,
            (sourceContext, contentTuple) =>
            {
                var ((directory, paths), rootNamespace) = contentTuple;
                sourceContext.CancellationToken.ThrowIfCancellationRequested();

                builder.Append($"""
                    // <auto-generated/>

                    using ModContent = Terraria.ModLoader.ModContent;
                    using AssetRequestMode = ReLogic.Content.AssetRequestMode;

                    using SoundStyle = Terraria.Audio.SoundStyle;
                    using Effect = Microsoft.Xna.Framework.Graphics.Effect;
                    using Texture2D = Microsoft.Xna.Framework.Graphics.Texture2D;

                    namespace {rootNamespace};


                    """);

                var indent = 0;
                foreach(var pathPart in directory.Split('/', StringSplitOptions.RemoveEmptyEntries)) {
                    if(pathPart.StartsWith('.')) continue; // NOTE: skips folders like '.compiled' in effects folder

                    AppendLineIndented(builder, indent, $"internal partial class {pathPart} {{");
                    indent++;
                }

                foreach(var path in paths) {
                    var extension = Path.GetExtension(path);
                    var modAssetPath = $"{rootNamespace}/{path[..^extension.Length]}";
                    var name = Path.GetFileName(modAssetPath);

                    var isTexture = TextureExtensions.Contains(extension);
                    var isEffect = EffectExtensions.Contains(extension);
                    var isAudio = AudioExtensions.Contains(extension);

                    if(isTexture || isEffect) {
                        var assetTypeString = isTexture ? "Texture2D" : "Effect";

                        AppendLineIndented(
                            builder,
                            indent,
                            $"public static ReLogic.Content.Asset<{assetTypeString}> ASSET_{name} => ModContent.Request<{assetTypeString}>(\"{modAssetPath}\", AssetRequestMode.ImmediateLoad);");

                        AppendLineIndented(
                            builder,
                            indent,
                            $"public static {assetTypeString} {name} => ASSET_{name}.Value;");

                        AppendLineIndented(
                            builder,
                            indent,
                            $"public static string KEY_{name} = \"{modAssetPath}\";");
                    }
                    else if(isAudio) {
                        var assetTypeString = "SoundStyle";

                        AppendLineIndented(
                            builder,
                            indent,
                            $"private static {assetTypeString} _{name} = default;");

                        AppendLineIndented(
                            builder,
                            indent,
                            $"public static string KEY_{name} = \"{modAssetPath}\";");

                        AppendLineIndented(
                            builder,
                            indent,
                            $$"""
                            public static {{assetTypeString}} {{name}} {
                                get {
                                    if (_{{name}} == default({{assetTypeString}})) {
                                        _{{name}} = new {{assetTypeString}}("{{modAssetPath}}");
                                    }

                                    return _{{name}};
                                }
                            }
                            """);
                    }
                }

                while(indent > 0) {
                    indent--;
                    AppendLineIndented(builder, indent, "}");
                }

                string source = builder.ToString();
                builder.Clear();

                sourceContext.AddSource($"{directory.Replace('/', '.')}.cs", source);
            }
        );
    }

    static void AppendLineIndented(StringBuilder builder, int indent, string text) {
        foreach(var line in text.Split('\n')) {
            if(line.Length == 0) continue;

            builder.Append(' ', indent * 4);
            builder.Append(line);
            builder.Append('\n');
        }
    }
}